name: "Run pytest"

on:
  push:
    branches:
      - main

jobs:
  checkout:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        apt-get install pipx
        pipx install poetry
    - name: Build package
      run: poetry install --with test
    - name: Run tests
      run: pytest -rF